### PR TITLE
fix issues 10 and ...

### PR DESCRIPTION
**Pull request by UnknownNull**

### CODE REVIEW

**Comment by UnknownNull** [comment]
5:40 am by me right now
https://github.com/DanteDEVS/MurderMysteryLED/commit/cc3c859f8a3e0c1627719c4130fd0f1326f8888c

**Comment by DanteDEVS** [comment]
Looks valid however most of ur commits are reverting back but the rest looks good.
if u didnt check {well i dont think u can} i have done changes aswell to fix #10

**Comment by DanteDEVS** [comment]
so i might just close this or add a few changes but most here can cause issues since u reverting back

**Comment by DanteDEVS** [comment]
Closed

**Pull request closed without merging**
